---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-app
    service: backend
  name: prod-app-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-app
      service: backend
  template:
    metadata:
      labels:
        app: prod-app
        service: backend
    spec:
      containers:
        - image: dannecron/netology-devops-k8s-app:backend-latest
          imagePullPolicy: Always
          name: netology-backend
          env:
            - name: DATABASE_URL
              value: "postgresql://db_user:db_passwd@postgres:5432/news"
          ports:
            - name: web
              containerPort: 9000
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: prod-backend
  namespace: default
spec:
  ports:
    - name: web
      port: 9000
  selector:
    app: prod-app
    service: backend
