---
version: '3.8'

services:
  postgres:
    image: postgres:12.11-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "25432:5432"
    volumes:
      - netology_pgdata:/var/lib/postgresql/data/pgdata
      - netology_pgdump:/opt/pgdump

volumes:
  netology_pgdata:
  netology_pgdump: