---
version: '3.8'

services:
  postgres:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_database
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "25432:5432"
    volumes:
      - netology_pgdata:/var/lib/postgresql/data/pgdata
      - ./dump:/opt/dump

volumes:
  netology_pgdata:
