---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}-postgres-pv-volume
  labels:
    type: local
    app: {{ .Chart.Name }}-{{ .Values.environment }}
    service: database
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.database.hostVolumePath | quote }}
