---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}-{{.Release.Namespace}}-postgres-pv-volume
  labels:
    type: local
    app: {{ .Chart.Name }}-{{ .Values.environment }}
    service: database
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ include "project.database.pv.hostpath" . | quote }}
