---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}-postgres-pv-claim
  labels:
    app: {{ .Chart.Name }}-{{ .Values.environment }}
    service: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
