---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-{{ .Values.environment }}
    service: frontend
  name: {{ .Chart.Name }}-{{ .Values.environment }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.environment }}
      service: frontend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.environment }}
        service: frontend
    spec:
      containers:
        - image: {{ .Values.image.name }}:frontend-latest
          imagePullPolicy: Always
          name: frontend
          env:
            - name: BASE_URL
              value: "http://{{ .Chart.Name }}-{{ .Values.environment }}-backend:9000"
          ports:
            - name: web
              containerPort: 80
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
