---
version: '3.8'

services:
  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    volumes:
      - netology_mysql_data:/var/lib/mysql
      - ./dump:/opt/dump
      - ./inno_db.cnf:/etc/mysql/conf.d/inno_db.cnf

volumes:
  netology_mysql_data: