{
 "title": "node-exporter",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Load Average",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(node_load1{})", "legendFormat": "__auto" },
    { "expr": "avg(node_load5{})", "legendFormat": "__auto" },
    { "expr": "avg(node_load15{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Свободная оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_Active_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Нагрузка на node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободное место на диске",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}