---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}-backend
spec:
  ports:
    - name: web
      port: 9000
  selector:
    app: {{ .Chart.Name }}-{{ .Values.environment }}
    service: backend
